# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f0339e991a812ab7867f7658f3548517978d9c40175b6b6b6b47f9493b083ba15253b29848b1b2596c6e1da1053fc08e2852ff07ca436bfd9616844dea53cff

test:
  secret_key_base: 2bdd2e51bad084affd624528b64cf8ebfb5c71eda27656a0a913aeeee1eb595138ff920192e24efed62e27e76e23f45f1167f54fd35bd859e3b1a193eb6bef7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
